name: ui_kit
description: UI Kit for the main app
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2